#!/usr/bin/python3
"""factorize given set of numbers in a file to product of two small numbers"""
from sys import argv

def factor(check_int):
    """"find two small multiply of a given number"""
    i = 2

    if check_int < 2:
        return
    
    while check_int % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(check_int, check_int / i, i))

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            check_int = int(line.split('\n')[0])
            factor(check_int)
            line = file.readline()
except:
    pass