#!/usr/bin/python3
import sys

def factors(n):
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return n // i, i
    return 1, n

source = sys.argv[1]

with open(source, "r") as f:
    for line in f:
        n = int(line)
        p, q = factors(n)
        print("{:d}={:d}*{:d}".format(n, p, q))
