#!/usr/bin/python3
import sys
import signal

def factors(n):
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return n // i, i
    return 1, n

def handler(signum, frame):
    raise Exception("Time is up!")

# This sets the alarm signal handler to your handler function.
signal.signal(signal.SIGALRM, handler)

# This schedules an alarm for 5 seconds in the future.
signal.alarm(5)

try:    
    source = sys.argv[1]

    with open(source, "r") as f:
        for line in f:
            n = int(line)
            p, q = factors(n)
            print("{:d}={:d}*{:d}".format(n, p, q))

except Exception:
    print(Exception)
